### ISSUE TITLE
rosdep install on docker (ubuntu 16.04)

### ISSUE THREAD

**Issue by bergq1** [ros-infrastructure/rosdep#477] opened 2016-09-27 11:53 UTC
Step 31 : RUN rosdep install --from-paths src --ignore-src --rosdistro kinetic -y
 ---> Running in 66adf308c6a8

ERROR: Rosdep experienced an error: [Errno 2] No such file or directory
Please go to the rosdep page [1] and file a bug report with the stack trace below.
[1] : http://www.ros.org/wiki/rosdep

rosdep version: 0.11.5

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/rosdep2/main.py", line 136, in rosdep_main
    exit_code = _rosdep_main(args)
  File "/usr/lib/python2.7/dist-packages/rosdep2/main.py", line 353, in _rosdep_main
    return _package_args_handler(command, parser, options, args)
  File "/usr/lib/python2.7/dist-packages/rosdep2/main.py", line 447, in _package_args_handler
    return command_handlers[command](lookup, packages, options)
  File "/usr/lib/python2.7/dist-packages/rosdep2/main.py", line 654, in command_install
    installer.install(uninstalled, **install_options)
  File "/usr/lib/python2.7/dist-packages/rosdep2/installers.py", line 485, in install
    verbose=verbose, quiet=quiet)
  File "/usr/lib/python2.7/dist-packages/rosdep2/installers.py", line 535, in install_resolved
    result = subprocess.call(sub_command)
  File "/usr/lib/python2.7/subprocess.py", line 523, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

executing command [sudo -H apt-get install -y python-matplotlib]
The command '/bin/sh -c rosdep install --from-paths src --ignore-src --rosdistro kinetic -y' returned a non-zero code: 1

**Comment by tfoote** [comment] 2016-09-27 20:07
This is a duplicate of #473 use the option `--as-root apt:false`.

**Closed by tfoote** 2016-09-27 20:07 UTC
