### ISSUE TITLE
ERROR: Rosdep experienced an internal error. (Bad Installer [pip] ...)

### ISSUE THREAD

**Issue by japzi** [ros-infrastructure/rosdep#416] opened 2015-09-26 02:55 UTC
OSX Yosamite 10.10.3
$ rosdep install --from-paths src --ignore-src --rosdistro jade -y --skip-keys ogre --skip-keys gazebo
ERROR: Rosdep experienced an internal error.
Please go to the rosdep page [1] and file a bug report with the message below.
[1] : http://www.ros.org/wiki/rosdep

rosdep version: 0.11.3

Bad installer [pip]: Command '['pip', 'show', 'nose']' returned non-zero exit status 1

**Comment by wjwwood** [comment] 2015-09-26 03:23
I believe this is a duplicate of https://github.com/ros-infrastructure/rosdep/issues/414

**Closed by wjwwood** 2015-09-26 03:23 UTC

**Comment by japzi** [comment] 2015-09-26 03:57
yes it is, didn't realize a new version 0.11.4 was release. went through the step without an issue with above 0.11.4.

**Comment by wjwwood** [comment] 2015-09-26 08:45
@japzi no problem, sorry for the interruption.
