### ISSUE TITLE
rosdep install fails for metapackages

### ISSUE THREAD

**Issue by ipa-fmw** [ros-infrastructure/rosdep#430] opened 2015-11-24 16:32 UTC
rosdep install fails to install dependencies from metapackages. 

We tracked down the error to `rospkg_loader.py`:
`get_rosdeps` (https://github.com/ros-infrastructure/rosdep/blob/master/src/rosdep2/rospkg_loader.py#L120) returns an empty list for metapackages. Comment in https://github.com/ros-infrastructure/rosdep/blob/master/src/rosdep2/rospkg_loader.py#L136 is `# stacks currently do not have rosdeps of their own, implicit or otherwise`.

Is this a left-over from pre-catkin and a bug? or is this done by purpose?

Example is the care-o-bot metapackages in https://github.com/ipa320/care-o-bot. Cloning that into an empty catkin workspace and running `rosdep install --from-path src -i -y` does not install any dependencies.

**Comment by wjwwood** [comment] 2017-07-28 01:32
I know this is an old bug, but I'm not sure if this is by design or not. @dirk-thomas do you know of any conceptual reason that metapackages should not get their dependencies installed?

**Comment by NikolausDemmel** [comment] 2017-07-28 11:19
I personally can't think of any reason and agree that it should be changed.

**Comment by ipa-mdl** [comment] 2017-07-28 11:34
Needs to be fixed in [rospkg_loader.py](https://github.com/ros-infrastructure/rosdep/blob/master/src/rosdep2/rospkg_loader.py#L136)

**Comment by dirk-thomas** [comment] 2017-07-28 12:19
I don't see a reason why metapackages should be treated differently either.

**Closed** 2017-07-31 21:20 UTC
Labels: bug
