### ISSUE TITLE
Dependencies fail to install on proxy

### ISSUE THREAD

**Issue by wboler05** [ros-infrastructure/rosdep#711] opened 2019-10-01 21:23 UTC
Hi all,

This may be a bad fix, but on my system I was unable to get the dependencies to install across a proxy.  I noticed that the command "sudo -H apt install ..." is being used when calling for system installs of necessary dependencies.  In order to use the proxy on my system, the "-E" flag must be passed to sudo in order to pass the environment settings.  I modified installers.py to get this running, but I'm hoping there is a better way to go about doing this. 

Will

**Comment by tfoote** [comment] 2019-10-16 23:36
This looks like a duplicate of #271 which has a discussion and a direction. 

In the mean time you can configure the proxies system wide like in [this answer](https://answers.ros.org/question/54150/rosdep-initialization-error/)

**Closed by tfoote** 2019-10-16 23:36 UTC
Labels: duplicate
