### ISSUE TITLE
rosdep init Website may be down

### ISSUE THREAD

**Issue by AlirezAghaie** [ros-infrastructure/rosdep#493] opened 2017-01-02 13:55 UTC
sudo rosdep init
is returning 
`ERROR: cannot download default sources list from:
https://raw.githubusercontent.com/ros/rosdistro/master/rosdep/sources.list.d/20-default.list
Website may be down.`
i dont have any proxy running behind ( and can't get one actually ) .
how can i solve this ?
i've read many pages on this problem but can't solve it yet.

**Comment by wjwwood** [comment] 2017-01-03 20:50
Please try again later or make sure your internet is working correctly, as this message suggests the `Website may be down`.

Duplicate of https://github.com/ros-infrastructure/rosdep/issues/492

**Closed by wjwwood** 2017-01-03 20:50 UTC
