### ISSUE TITLE
rosdep error when running on verbose mode

### ISSUE THREAD

**Issue by bergercookie** [ros-infrastructure/rosdep#487] opened 2016-11-11 21:05 UTC
Error occurs when running rosdep with the --verbose flag:
```
$ rosdep install --from-paths src --ignore-src --rosdistro kinetic -y --verbose

...

  File "/Users/nick/Library/Python/2.7/lib/python2.7/site-packages/rosdep2/main.py", line 634, in command_install
    print("uninstalled dependencies are: [%s]"%(', '.join([', '.join(pkg) for pkg in [v for k,v in uninstalled]])))
TypeError: sequence item 0: expected string, HomebrewResolution found
```
Complete  error log is provided [here](https://github.com/ros-infrastructure/rosdep/files/586744/rosdep_error.txt)

The platform is OSX 10.11.6

**Comment by tfoote** [comment] 2016-11-11 21:33
Thanks for the report this looks like a duplicate of #486

**Closed by tfoote** 2016-11-11 21:33 UTC
