### ISSUE TITLE
rosdep cannot verify homebrew vtk installation on osx-10.9.5

### ISSUE THREAD

**Issue by Juxi** [ros-infrastructure/rosdep#363] opened 2014-11-28 02:03 UTC
```
rosdep install --from-paths src --ignore-src --rosdistro indigo -y
executing command [brew install vtk --python --qt]
Warning: vtk-6.1.0 already installed
ERROR: the following rosdeps failed to install
  homebrew: Failed to detect successful installation of [vtk --python --qt]
```

and the stack trace is:

```
ERROR: Rosdep experienced an error: sequence item 0: expected string, HomebrewResolution found
Please go to the rosdep page [1] and file a bug report with the stack trace below.
[1] : http://www.ros.org/wiki/rosdep

rosdep version: 0.10.33

Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/rosdep2/main.py", line 136, in rosdep_main
    exit_code = _rosdep_main(args)
  File "/Library/Python/2.7/site-packages/rosdep2/main.py", line 345, in _rosdep_main
    return _package_args_handler(command, parser, options, args)
  File "/Library/Python/2.7/site-packages/rosdep2/main.py", line 435, in _package_args_handler
    return command_handlers[command](lookup, packages, options)
  File "/Library/Python/2.7/site-packages/rosdep2/main.py", line 619, in command_install
    uninstalled, errors = installer.get_uninstalled(packages, implicit=options.recursive, verbose=options.verbose)
  File "/Library/Python/2.7/site-packages/rosdep2/installers.py", line 413, in get_uninstalled
    print("resolution: %s [%s]"%(installer_key, ', '.join(resolved)))
TypeError: sequence item 0: expected string, HomebrewResolution found
```

According to Homebrew `vtk` is installed:

```
brew info vtk
vtk: stable 6.1.0, HEAD
http://www.vtk.org
/usr/local/Cellar/vtk/6.1.0 (3121 files, 123M) *
  Built from source
From: https://github.com/homebrew/homebrew-science/blob/master/vtk.rb
==> Dependencies
Build: cmake ✔
Recommended: boost ✔, fontconfig ✔, hdf5 ✔, jpeg ✔, libpng ✔, libtiff ✔
Optional: qt ✔, qt5 ✘
```

Any ideas what might be the reason for that?

**Comment by ahundt** [comment] 2015-01-20 04:44
I'm still getting a similar error:

```
○ rosdep install --from-paths src --ignore-src --rosdistro indigo -y
executing command [brew install vtk --with-qt]
Warning: vtk-6.1.0_1 already installed
ERROR: the following rosdeps failed to install
  homebrew: Failed to detect successful installation of [vtk --with-qt]
```


I'm on step 2.1.2 of http://wiki.ros.org/indigo/Installation/OSX/Homebrew/Source

Is there a workaround I could use, and can the wiki step be updated with it?

Thanks for your help.

**Comment by wjwwood** [comment] 2015-01-20 18:45
@ahundt a workaround would be to install `vtk` yourself and then run `rosdep ... --skip-keys libvtk` where `...` are the other arguments you were passing to `rosdep`.

Can you post the output of `brew info vtk`? It maybe that you just had `vtk` installed before but without the right options enabled. `rosdep` cannot uninstall and reinstall with the correction options itself, so you'd have to do that yourself.

**Comment by wjwwood** [comment] 2015-09-23 22:29
I can't reproduce this with the latest version of `rosdep` and/or Homebrew. I'll close it for now, but anyone should feel free to comment if they run into it again.

**Closed by wjwwood** 2015-09-23 22:29 UTC
