### ISSUE TITLE
Unrecognized Version 10.11 

### ISSUE THREAD

**Issue by eduran0826** [ros-infrastructure/rosdep#423] opened 2015-10-07 18:26 UTC
Rosdep does not recognized OS 10.11 on a Mac.

**Comment by wjwwood** [comment] 2015-10-07 18:37
I think this is a duplicate of https://github.com/ros-infrastructure/rosdep/issues/421, I'll try to get this resolved today.

**Closed by wjwwood** 2015-10-07 18:37 UTC
