### ISSUE TITLE
rosdep2 missing support for condition attribute

### ISSUE THREAD

**Issue by JWhitleyAStuff** [ros-infrastructure/rosdep#676] opened 2019-04-10 22:07 UTC
In #654, support was added to `rosdep` for the new Package Format Specification 3 (REP-149) `conditional` attribute. However, `rosdep2` seems to have missed out on the love. This is causing `dev` builds to fail on the build farm (and local tests show dependency resolution failure as well when `python-rosdep2` is installed) when the `condition` attribute is present in package.xml files.

I'm not really sure where the line falls between `rosdep` and `rosdep2` or I would create a PR to fix the issue. Here are some affected builds on the build farm(s):

Kinetic: http://build.ros.org/job/Kdev__ml_classifiers__ubuntu_xenial_amd64/4/console
Crystal: http://build.ros2.org/job/Cdev__ml_classifiers__ubuntu_bionic_amd64/1/console

Thanks to @nuclearsandwich for helping me track down the failures.

**Comment by dirk-thomas** [comment] 2019-04-10 22:17
There is only one `rosdep` upstream repository and that is this repo. The Python package within uses the module name `rosdep2`. The Debian package we provide through the ROS apt repos uses the name `python(3)-rosdep` and should be up-to-date with the latest tagged release of this repo (atm `0.15.1`).

`python-rosdep2` is a Debian package created by Debian maintainers (https://packages.debian.org/search?keywords=python-rosdep2). That seems to be of the same version though. You shouldn't mix this with packages provided by the ROS repos though. The buildfarm doesn't use this package.

Your package is the first one being processed on the buildfarm which uses the condition attributes to select between ROS 1 and ROS 2. Somewhere in the pipeline there is a problem since nobody has ever tried that. The problem is unlikely to be in `rosdep` itself though since it doesn't know about condition attributes.

Since you already created a separate ticket I will go ahead and close this one.

**Closed by dirk-thomas** 2019-04-10 22:17 UTC
Labels: duplicate
